title: "Shah Kamran Ahmad"
email: shahkamran@live.com
timezone: UTC
baseurl: ""
permalink: "/:title/"
logo: "assets/images/logo.png"
favicon: "assets/images/favicon.ico"
author: Shah Kamran
paginate: 30
locale: en_us
lang: en_us
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
disqus: "https-shah-kamran-github-io"
google_analytics: "UA-123456789-1"

# Authors
authors:
  shah:
    name: Shah Kamran
    display_name: Shah
    avatar: "assets/images/sal.png"
    email: shahkamran@live.com
    web: https://www.shah-kamran@github.io/
    twitter: https://twitter.com/wowthemesnet
    description: "Author of Affiliates, a template available for WordPress, HTML, Ghost and Jekyll. You are currently previewing Jekyll template demo."
  sibgha:
    name: Sibgha Ahmad
    display_name: Sibgha
    avatar: "assets/images/john.png"
    email: shahkamran@live.com
    web: https://www.shah-kamran@github.io/
    twitter: https://twitter.com/wowthemesnet
    description: "This is the author box. Write a short description of the author here. You are currently previewing Affiliates theme demo, a Jekyll template compatible with Github pages."

# Social
social:
  instagram: https://www.instagram.com/bootstrapstarter/
  facebook: https://www.facebook.com/bootstrapstartercom-346329609045284
  twitter: https://twitter.com/bstartercom

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
